/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import { customInstance } from "../../../../lib/fetch";
import type { GetTranslationOutputDto } from "../../model";

export const translationPublicControllerGetTranslation = (
  locale: string,
  namespace: string,
  signal?: AbortSignal,
) => {
  return customInstance<GetTranslationOutputDto>({
    url: `/translation/public/get-translation/${locale}/${namespace}`,
    method: "GET",
    signal,
  });
};

export const getTranslationPublicControllerGetTranslationQueryKey = (
  locale: string,
  namespace: string,
) => {
  return [
    `/translation/public/get-translation/${locale}/${namespace}`,
  ] as const;
};

export const getTranslationPublicControllerGetTranslationQueryOptions = <
  TData = Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>,
  TError = unknown,
>(
  locale: string,
  namespace: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>,
        TError,
        TData
      >
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getTranslationPublicControllerGetTranslationQueryKey(locale, namespace);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>
  > = ({ signal }) =>
    translationPublicControllerGetTranslation(locale, namespace, signal);

  return {
    queryKey,
    queryFn,
    enabled: !!(locale && namespace),
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData> };
};

export type TranslationPublicControllerGetTranslationQueryResult = NonNullable<
  Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>
>;
export type TranslationPublicControllerGetTranslationQueryError = unknown;

export function useTranslationPublicControllerGetTranslation<
  TData = Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>,
  TError = unknown,
>(
  locale: string,
  namespace: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData>;
};
export function useTranslationPublicControllerGetTranslation<
  TData = Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>,
  TError = unknown,
>(
  locale: string,
  namespace: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>,
          TError,
          TData
        >,
        "initialData"
      >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };
export function useTranslationPublicControllerGetTranslation<
  TData = Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>,
  TError = unknown,
>(
  locale: string,
  namespace: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> };

export function useTranslationPublicControllerGetTranslation<
  TData = Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>,
  TError = unknown,
>(
  locale: string,
  namespace: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof translationPublicControllerGetTranslation>>,
        TError,
        TData
      >
    >;
  },
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getTranslationPublicControllerGetTranslationQueryOptions(
    locale,
    namespace,
    options,
  );

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
}
