/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProfileImport } from './routes/profile'
import { Route as LoginImport } from './routes/login'
import { Route as WsImport } from './routes/_ws'
import { Route as WsMenuMultiplayerImport } from './routes/_ws.menu-multiplayer'
import { Route as WsLobbiesImport } from './routes/_ws.lobbies'
import { Route as WsCreateLobbyImport } from './routes/_ws.create-lobby'
import { Route as WsLobbyLobbyIdImport } from './routes/_ws.lobby.$lobbyId'
import { Route as WsGameGameIdImport } from './routes/_ws.game.$gameId'

// Create/Update Routes

const ProfileRoute = ProfileImport.update({
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const WsRoute = WsImport.update({
  id: '/_ws',
  getParentRoute: () => rootRoute,
} as any)

const WsMenuMultiplayerRoute = WsMenuMultiplayerImport.update({
  path: '/menu-multiplayer',
  getParentRoute: () => WsRoute,
} as any)

const WsLobbiesRoute = WsLobbiesImport.update({
  path: '/lobbies',
  getParentRoute: () => WsRoute,
} as any)

const WsCreateLobbyRoute = WsCreateLobbyImport.update({
  path: '/create-lobby',
  getParentRoute: () => WsRoute,
} as any)

const WsLobbyLobbyIdRoute = WsLobbyLobbyIdImport.update({
  path: '/lobby/$lobbyId',
  getParentRoute: () => WsRoute,
} as any)

const WsGameGameIdRoute = WsGameGameIdImport.update({
  path: '/game/$gameId',
  getParentRoute: () => WsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_ws': {
      id: '/_ws'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof WsImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/_ws/create-lobby': {
      id: '/_ws/create-lobby'
      path: '/create-lobby'
      fullPath: '/create-lobby'
      preLoaderRoute: typeof WsCreateLobbyImport
      parentRoute: typeof WsImport
    }
    '/_ws/lobbies': {
      id: '/_ws/lobbies'
      path: '/lobbies'
      fullPath: '/lobbies'
      preLoaderRoute: typeof WsLobbiesImport
      parentRoute: typeof WsImport
    }
    '/_ws/menu-multiplayer': {
      id: '/_ws/menu-multiplayer'
      path: '/menu-multiplayer'
      fullPath: '/menu-multiplayer'
      preLoaderRoute: typeof WsMenuMultiplayerImport
      parentRoute: typeof WsImport
    }
    '/_ws/game/$gameId': {
      id: '/_ws/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof WsGameGameIdImport
      parentRoute: typeof WsImport
    }
    '/_ws/lobby/$lobbyId': {
      id: '/_ws/lobby/$lobbyId'
      path: '/lobby/$lobbyId'
      fullPath: '/lobby/$lobbyId'
      preLoaderRoute: typeof WsLobbyLobbyIdImport
      parentRoute: typeof WsImport
    }
  }
}

// Create and export the route tree

interface WsRouteChildren {
  WsCreateLobbyRoute: typeof WsCreateLobbyRoute
  WsLobbiesRoute: typeof WsLobbiesRoute
  WsMenuMultiplayerRoute: typeof WsMenuMultiplayerRoute
  WsGameGameIdRoute: typeof WsGameGameIdRoute
  WsLobbyLobbyIdRoute: typeof WsLobbyLobbyIdRoute
}

const WsRouteChildren: WsRouteChildren = {
  WsCreateLobbyRoute: WsCreateLobbyRoute,
  WsLobbiesRoute: WsLobbiesRoute,
  WsMenuMultiplayerRoute: WsMenuMultiplayerRoute,
  WsGameGameIdRoute: WsGameGameIdRoute,
  WsLobbyLobbyIdRoute: WsLobbyLobbyIdRoute,
}

const WsRouteWithChildren = WsRoute._addFileChildren(WsRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof WsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/create-lobby': typeof WsCreateLobbyRoute
  '/lobbies': typeof WsLobbiesRoute
  '/menu-multiplayer': typeof WsMenuMultiplayerRoute
  '/game/$gameId': typeof WsGameGameIdRoute
  '/lobby/$lobbyId': typeof WsLobbyLobbyIdRoute
}

export interface FileRoutesByTo {
  '': typeof WsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/create-lobby': typeof WsCreateLobbyRoute
  '/lobbies': typeof WsLobbiesRoute
  '/menu-multiplayer': typeof WsMenuMultiplayerRoute
  '/game/$gameId': typeof WsGameGameIdRoute
  '/lobby/$lobbyId': typeof WsLobbyLobbyIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_ws': typeof WsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/_ws/create-lobby': typeof WsCreateLobbyRoute
  '/_ws/lobbies': typeof WsLobbiesRoute
  '/_ws/menu-multiplayer': typeof WsMenuMultiplayerRoute
  '/_ws/game/$gameId': typeof WsGameGameIdRoute
  '/_ws/lobby/$lobbyId': typeof WsLobbyLobbyIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/profile'
    | '/create-lobby'
    | '/lobbies'
    | '/menu-multiplayer'
    | '/game/$gameId'
    | '/lobby/$lobbyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/login'
    | '/profile'
    | '/create-lobby'
    | '/lobbies'
    | '/menu-multiplayer'
    | '/game/$gameId'
    | '/lobby/$lobbyId'
  id:
    | '__root__'
    | '/_ws'
    | '/login'
    | '/profile'
    | '/_ws/create-lobby'
    | '/_ws/lobbies'
    | '/_ws/menu-multiplayer'
    | '/_ws/game/$gameId'
    | '/_ws/lobby/$lobbyId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  WsRoute: typeof WsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
}

const rootRouteChildren: RootRouteChildren = {
  WsRoute: WsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_ws",
        "/login",
        "/profile"
      ]
    },
    "/_ws": {
      "filePath": "_ws.tsx",
      "children": [
        "/_ws/create-lobby",
        "/_ws/lobbies",
        "/_ws/menu-multiplayer",
        "/_ws/game/$gameId",
        "/_ws/lobby/$lobbyId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/_ws/create-lobby": {
      "filePath": "_ws.create-lobby.tsx",
      "parent": "/_ws"
    },
    "/_ws/lobbies": {
      "filePath": "_ws.lobbies.tsx",
      "parent": "/_ws"
    },
    "/_ws/menu-multiplayer": {
      "filePath": "_ws.menu-multiplayer.tsx",
      "parent": "/_ws"
    },
    "/_ws/game/$gameId": {
      "filePath": "_ws.game.$gameId.tsx",
      "parent": "/_ws"
    },
    "/_ws/lobby/$lobbyId": {
      "filePath": "_ws.lobby.$lobbyId.tsx",
      "parent": "/_ws"
    }
  }
}
ROUTE_MANIFEST_END */
