/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type AttackRange = (typeof AttackRange)[keyof typeof AttackRange];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttackRange = {
  melee: "melee",
  long: "long",
  versatile: "versatile",
} as const;
