/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { AttackRange } from "./attackRange";
import type { AttackType } from "./attackType";
import type { DiceResponseDto } from "./diceResponseDto";
import type { PerkResponseDto } from "./perkResponseDto";

export interface AttackResponseDto {
  range: AttackRange;
  type: AttackType;
  id: string;
  dices: DiceResponseDto[];
  perks: PerkResponseDto[];
}
