/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type AttackType = (typeof AttackType)[keyof typeof AttackType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AttackType = {
  regular: "regular",
  super: "super",
} as const;
