/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { Tile } from "./tile";

export interface Board {
  tiles: Tile[];
  width: number;
  height: number;
}
