/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type CampaignStatus =
  (typeof CampaignStatus)[keyof typeof CampaignStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignStatus = {
  AVAILABLE: "AVAILABLE",
  COMING_SOON: "COMING_SOON",
  DISABLED: "DISABLED",
} as const;
