/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type CampaignStageStatus =
  (typeof CampaignStageStatus)[keyof typeof CampaignStageStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CampaignStageStatus = {
  AVAILABLE: "AVAILABLE",
  COMING_SOON: "COMING_SOON",
  DISABLED: "DISABLED",
} as const;
