/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export interface Characteristic {
  baseHealthPoints: number;
  baseManaPoints: number;
  baseArmorClass: number;
  baseMovementPoints: number;
  baseActionPoints: number;
}
