/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export interface CharacteristicResponseDto {
  baseHealthPoints: number;
  healthPoints: number;
  baseManaPoints: number;
  manaPoints: number;
  baseArmorClass: number;
  armorClass: number;
  baseMovementPoints: number;
  movementPoints: number;
  baseActionPoints: number;
  actionPoints: number;
}
