/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { ItemTypeChestTrap } from "./itemTypeChestTrap";

export interface ChestTrapResponseDto {
  type: ItemTypeChestTrap;
  name: string;
  level: number;
  imgUrl: string;
}
