/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { ConfigCampaign } from "./configCampaign";

export interface Config {
  nbPlayersMax: number;
  campaign: ConfigCampaign;
}
