/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { ConfigCampaignStage } from "./configCampaignStage";

export interface ConfigCampaign {
  id: string;
  nbStages: number;
  stage: ConfigCampaignStage;
}
