/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export interface DiceResponseDto {
  name: string;
  values: string[];
  minValue: number;
  maxValue: number;
  meanValue: number;
}
