import type { InteractiveEntityKindDoor } from "./interactiveEntityKindDoor";
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { TileEntityTypeInteractiveEntity } from "./tileEntityTypeInteractiveEntity";

export interface DoorEntityResponseDto {
  type: TileEntityTypeInteractiveEntity;
  kind: InteractiveEntityKindDoor;
  isVisible: boolean;
  isBlocking: boolean;
  canInteract: boolean;
}
