/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { PlayableHeroEntity } from "./playableHeroEntity";
import type { PlayableMonsterEntity } from "./playableMonsterEntity";

export type GameResponseDtoPlayableEntitiesItem =
  | PlayableHeroEntity
  | PlayableMonsterEntity;
