/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type GameStatus = (typeof GameStatus)[keyof typeof GameStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GameStatus = {
  PREPARE_FOR_BATTLE: "PREPARE_FOR_BATTLE",
  BATTLE_ONGOING: "BATTLE_ONGOING",
} as const;
