/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { CampaignStatus } from "./campaignStatus";
import type { StageSchema } from "./stageSchema";

export interface GetCampaignOutputDto {
  status: CampaignStatus;
  currentStage: StageSchema;
  nbStages: number;
  id: string;
}
