import type { Characteristic } from "./characteristic";
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { GetHeroDetailsOutputDtoClass } from "./getHeroDetailsOutputDtoClass";

export interface GetHeroDetailsOutputDto {
  id: string;
  class: GetHeroDetailsOutputDtoClass;
  name: string;
  characteristic: Characteristic;
  imgUrl: string;
}
