import type { Characteristic } from "./characteristic";
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { HeroClass } from "./heroClass";

export interface GetHeroDetailsOutputDto {
  class: HeroClass;
  id: string;
  name: string;
  characteristic: Characteristic;
  imgUrl: string;
}
