import type { Config } from "./config";
import type { GetLobbyOutputDtoStatus } from "./getLobbyOutputDtoStatus";
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { Host } from "./host";
import type { PlayableCharacter } from "./playableCharacter";
import type { Player } from "./player";

export interface GetLobbyOutputDto {
  id: string;
  host: Host;
  status: GetLobbyOutputDtoStatus;
  config: Config;
  players: Player[];
  playableCharacters: PlayableCharacter[];
}
