import type { GameResponseDto } from "./gameResponseDto";
import type { PlayerCurrentlyPlayingDto } from "./playerCurrentlyPlayingDto";
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { PlayerStatus } from "./playerStatus";

export interface GetUserGameStateOutputDto {
  yourStatus: PlayerStatus;
  game: GameResponseDto;
  playerCurrentlyPlaying: PlayerCurrentlyPlayingDto;
}
