/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { CurrentPhase } from "./currentPhase";
import type { GameResponseDto } from "./gameResponseDto";
import type { PlayerCurrentlyPlayingDto } from "./playerCurrentlyPlayingDto";

export interface GetUserGameStateOutputDto {
  yourStatus: CurrentPhase;
  game: GameResponseDto;
  playerCurrentlyPlaying: PlayerCurrentlyPlayingDto;
}
