/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type InteractiveEntityKindDoor =
  (typeof InteractiveEntityKindDoor)[keyof typeof InteractiveEntityKindDoor];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InteractiveEntityKindDoor = {
  door: "door",
} as const;
