import type { InventoryBackpackItem } from "./inventoryBackpackItem";
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { InventoryGearItem } from "./inventoryGearItem";
import type { StuffStorageCapacityResponseDto } from "./stuffStorageCapacityResponseDto";

export interface Inventory {
  gear: InventoryGearItem[];
  backpack: InventoryBackpackItem[];
  storageCapacity: StuffStorageCapacityResponseDto;
}
