/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { ItemType } from "./itemType";

export interface ItemResponseDto {
  type: ItemType;
  name: string;
  level: number;
  imgUrl: string;
}
