/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type ItemTypeArtifact =
  (typeof ItemTypeArtifact)[keyof typeof ItemTypeArtifact];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemTypeArtifact = {
  Artifact: "Artifact",
} as const;
