import type { Config } from "./config";
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { Host } from "./host";

export interface LobbyDto {
  nbPlayers: number;
  id: string;
  host: Host;
  config: Config;
}
