/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type PerkTrigger = (typeof PerkTrigger)[keyof typeof PerkTrigger];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PerkTrigger = {
  special_dice: "special_dice",
  once_per_attack: "once_per_attack",
} as const;
