/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type PerkName = (typeof PerkName)[keyof typeof PerkName];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PerkName = {
  reroll_one_dice: "reroll_one_dice",
  reroll_all_dices: "reroll_all_dices",
  critical_failure: "critical_failure",
  mana_leech: "mana_leech",
  breakable: "breakable",
  stop: "stop",
  frozen: "frozen",
  greater_healing: "greater_healing",
  ignore_armor_class: "ignore_armor_class",
  blood_price: "blood_price",
  turn_undead: "turn_undead",
  double_damage: "double_damage",
} as const;
