/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { PerkName } from "./perkName";
import type { PerkTrigger } from "./perkTrigger";

export interface PerkResponseDto {
  name: PerkName;
  trigger: PerkTrigger;
}
