/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type PlayableEntityFactionHero =
  (typeof PlayableEntityFactionHero)[keyof typeof PlayableEntityFactionHero];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlayableEntityFactionHero = {
  hero: "hero",
} as const;
