/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type PlayableEntityFaction =
  (typeof PlayableEntityFaction)[keyof typeof PlayableEntityFaction];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlayableEntityFaction = {
  hero: "hero",
  monster: "monster",
} as const;
