import type { CharacteristicResponseDto } from "./characteristicResponseDto";
import type { CoordResponseDto } from "./coordResponseDto";
import type { CurrentPhase } from "./currentPhase";
import type { HeroClass } from "./heroClass";
import type { Inventory } from "./inventory";
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { PlayableEntityFactionHero } from "./playableEntityFactionHero";
import type { PlayableEntityRace } from "./playableEntityRace";
import type { PlayableEntityType } from "./playableEntityType";

export interface PlayableHeroEntity {
  faction: PlayableEntityFactionHero;
  type: PlayableEntityType;
  race: PlayableEntityRace;
  currentPhase: CurrentPhase;
  class: HeroClass;
  inventory: Inventory;
  level: number;
  imgUrl: string;
  id: string;
  playedByUserId: string;
  name: string;
  initiative: number;
  coord: CoordResponseDto;
  isBlocking: boolean;
  characteristic: CharacteristicResponseDto;
}
