/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type PlayableEntityType =
  (typeof PlayableEntityType)[keyof typeof PlayableEntityType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlayableEntityType = {
  humanoid: "humanoid",
  gobelinoid: "gobelinoid",
  undead: "undead",
} as const;
