/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { ItemTypePotion } from "./itemTypePotion";

export interface PotionResponseDto {
  type: ItemTypePotion;
  name: string;
  level: number;
  imgUrl: string;
}
