/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { CampaignStageStatus } from "./campaignStageStatus";

export interface StageSchema {
  status: CampaignStageStatus;
  id: string;
  order: number;
}
