import type { PlayableEntityFaction } from "./playableEntityFaction";
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { TileEntityTypePlayableEntity } from "./tileEntityTypePlayableEntity";

export interface TilePlayableEntityResponseDto {
  type: TileEntityTypePlayableEntity;
  faction: PlayableEntityFaction;
  id: string;
  isBlocking: boolean;
}
