/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type TileEntityTypePlayableEntity =
  (typeof TileEntityTypePlayableEntity)[keyof typeof TileEntityTypePlayableEntity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TileEntityTypePlayableEntity = {
  PLAYABLE_ENTITY: "PLAYABLE_ENTITY",
} as const;
