/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { ChestEntityResponseDto } from "./chestEntityResponseDto";
import type { DoorEntityResponseDto } from "./doorEntityResponseDto";
import type { TrapEntityResponseDto } from "./trapEntityResponseDto";

export type TileEntitiesItemOneOf =
  | ChestEntityResponseDto
  | DoorEntityResponseDto
  | TrapEntityResponseDto;
