import type { NonInteractiveEntityKind } from "./nonInteractiveEntityKind";
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { TileEntityTypeNonInteractiveEntity } from "./tileEntityTypeNonInteractiveEntity";

export interface TileNonPlayableNonInteractiveEntityResponseDto {
  type: TileEntityTypeNonInteractiveEntity;
  kind: NonInteractiveEntityKind;
  isVisible: boolean;
  isBlocking: boolean;
  canInteract: boolean;
}
