import type { TileEntitiesItemOneOf } from "./tileEntitiesItemOneOf";
/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */
import type { TileNonPlayableNonInteractiveEntityResponseDto } from "./tileNonPlayableNonInteractiveEntityResponseDto";
import type { TilePlayableEntityResponseDto } from "./tilePlayableEntityResponseDto";

export type TileEntitiesItem =
  | TileNonPlayableNonInteractiveEntityResponseDto
  | TilePlayableEntityResponseDto
  | TileEntitiesItemOneOf;
