/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * DnD
 * The DnD API description
 * OpenAPI spec version: 1.0
 */

export type TrapName = (typeof TrapName)[keyof typeof TrapName];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TrapName = {
  pit: "pit",
} as const;
