version: '3.8'

services:
  rethinkdb:
    image: rethinkdb:latest
    container_name: rethinkdb
    restart: unless-stopped
    ports:
      - 8081:8080
      - 28015:28015
    volumes:
      - ./db_data:/data
