import { MigrationInterface, QueryRunner } from "typeorm";

export class RebootDbModels1741022678833 implements MigrationInterface {
    name = 'RebootDbModels1741022678833'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "analytics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "event_name" character varying NOT NULL, "data" json NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3c96dcbf1e4c57ea9e0c3144bff" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."campaign_status_enum" AS ENUM('AVAILABLE', 'COMING_SOON', 'DISABLED')`);
        await queryRunner.query(`CREATE TABLE "campaign" ("id" character varying NOT NULL, "status" "public"."campaign_status_enum" NOT NULL, CONSTRAINT "PK_0ce34d26e7f2eb316a3a592cdc4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."campaign_stage_status_enum" AS ENUM('AVAILABLE', 'COMING_SOON', 'DISABLED')`);
        await queryRunner.query(`CREATE TABLE "campaign_stage" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "order" integer NOT NULL, "max_level_loot" integer NOT NULL, "status" "public"."campaign_stage_status_enum" NOT NULL, "campaign_id" character varying NOT NULL, CONSTRAINT "PK_83bdcfdeac49ea7f7e2e294eff6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_090cbf92709adca8d9564daf84" ON "campaign_stage" ("campaign_id", "order") `);
        await queryRunner.query(`CREATE TYPE "public"."campaign_stage_progression_status_enum" AS ENUM('AVAILABLE', 'COMPLETED', 'LOCKED', 'STARTED')`);
        await queryRunner.query(`CREATE TABLE "campaign_stage_progression" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."campaign_stage_progression_status_enum" NOT NULL, "campaign_progression_id" uuid NOT NULL, "stage_id" uuid NOT NULL, CONSTRAINT "PK_e74c6f07db511ca4d54601c13c2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_da5afe8d6e472dd654037e30c0" ON "campaign_stage_progression" ("campaign_progression_id", "stage_id") `);
        await queryRunner.query(`CREATE TYPE "public"."campaign_progression_status_enum" AS ENUM('AVAILABLE', 'COMPLETED', 'LOCKED', 'STARTED')`);
        await queryRunner.query(`CREATE TABLE "campaign_progression" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "status" "public"."campaign_progression_status_enum" NOT NULL, "campaign_id" character varying NOT NULL, CONSTRAINT "PK_1bea5dedb1c1556c5814a0e01a3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_997e97791ec3aa7af5fb205907" ON "campaign_progression" ("campaign_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."playable_entity_condition_name_enum" AS ENUM('stopped', 'weakness', 'brokenArmor', 'doubleMovementPoints', 'trapProtection', 'doubleWeaponDamage')`);
        await queryRunner.query(`CREATE TABLE "playable_entity_condition" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."playable_entity_condition_name_enum" NOT NULL, "remaining_turns" integer NOT NULL, "playable_entity_id" uuid NOT NULL, CONSTRAINT "PK_6743761876c0e68a521f2e1bb51" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "current_game_event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "has_been_triggered" boolean NOT NULL, "game_id" uuid NOT NULL, "game_event_id" uuid NOT NULL, CONSTRAINT "PK_bcded9eb0cd871548a4b252d96c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "dice" ("name" character varying NOT NULL, "values" json NOT NULL, "min_value" integer NOT NULL, "max_value" integer NOT NULL, "mean_value" double precision NOT NULL, CONSTRAINT "PK_05b8e329851824881056dfae481" PRIMARY KEY ("name"))`);
        await queryRunner.query(`CREATE TABLE "item_perk_dice_throw" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "dice_name" character varying NOT NULL, "cause_id" uuid NOT NULL, CONSTRAINT "PK_17dae85fc9d98ba490da340b32c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."perk_trigger_enum" AS ENUM('special_dice', 'once_per_attack')`);
        await queryRunner.query(`CREATE TABLE "perk" ("name" character varying NOT NULL, "trigger" "public"."perk_trigger_enum" NOT NULL, CONSTRAINT "PK_e6e580c3461b79c3ec4d6774d56" PRIMARY KEY ("name"))`);
        await queryRunner.query(`CREATE TABLE "item_perk" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "perk_name" character varying NOT NULL, CONSTRAINT "PK_6f443a6979d8b493e702a7c2378" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."item_type_enum" AS ENUM('Weapon', 'Spell', 'ChestTrap', 'Potion', 'Artifact')`);
        await queryRunner.query(`CREATE TABLE "item" ("name" character varying NOT NULL, "type" "public"."item_type_enum" NOT NULL, "level" integer NOT NULL, "is_lootable_in_chest" boolean NOT NULL, CONSTRAINT "PK_c6ae12601fed4e2ee5019544ddf" PRIMARY KEY ("name"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a6c7fa282dcacbfe6247b28f13" ON "item" ("type") `);
        await queryRunner.query(`CREATE TYPE "public"."win_condition_name_enum" AS ENUM('defeat_all_monsters')`);
        await queryRunner.query(`CREATE TABLE "win_condition" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."win_condition_name_enum" NOT NULL, "nb_monsters_remaining" integer, "game_id" uuid, CONSTRAINT "PK_86b94d50369eee9f28315b99dee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0e32d7130c61d935786cd870b5" ON "win_condition" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."game_status_enum" AS ENUM('PREPARE_FOR_BATTLE', 'BATTLE_ONGOING')`);
        await queryRunner.query(`CREATE TABLE "game" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."game_status_enum" NOT NULL, "max_level_loot" integer NOT NULL, "board_id" uuid, "host_user_id" character varying NOT NULL, "game_master_user_id" character varying NOT NULL, CONSTRAINT "REL_0152ef021e5a686c048f756ebd" UNIQUE ("board_id"), CONSTRAINT "PK_352a30652cd352f552fef73dec5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."game_event_name_enum" AS ENUM('on_door_opening')`);
        await queryRunner.query(`CREATE TYPE "public"."game_event_action_enum" AS ENUM('spawn_monsters')`);
        await queryRunner.query(`CREATE TABLE "game_event" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."game_event_name_enum" NOT NULL, "action" "public"."game_event_action_enum" NOT NULL, "game_id" uuid, "starting_room_id" uuid, "door_coord_row" integer, "door_coord_column" integer, CONSTRAINT "REL_426f6d808d701deb57f05b03a6" UNIQUE ("starting_room_id"), CONSTRAINT "PK_d979b8a4d47b02b8f87322f33e0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "game_template" ("campaign_id" character varying NOT NULL, "board_id" uuid, CONSTRAINT "REL_a5713d51eb46a0faacea0236a0" UNIQUE ("board_id"), CONSTRAINT "PK_2de87db0299c0ff9184c791fbcc" PRIMARY KEY ("campaign_id"))`);
        await queryRunner.query(`CREATE TABLE "board" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "width" integer NOT NULL, "height" integer NOT NULL, CONSTRAINT "PK_865a0f2e22c140d261b1df80eb1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."interactive_entity_kind_enum" AS ENUM('door', 'trap', 'chest')`);
        await queryRunner.query(`CREATE TYPE "public"."interactive_entity_name_enum" AS ENUM('pit')`);
        await queryRunner.query(`CREATE TABLE "interactive_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "kind" "public"."interactive_entity_kind_enum" NOT NULL, "is_visible" boolean NOT NULL, "is_blocking" boolean NOT NULL, "can_interact" boolean NOT NULL, "name" "public"."interactive_entity_name_enum" DEFAULT 'pit', "tile_id" uuid NOT NULL, CONSTRAINT "PK_9398043ac6d1d90322a21bce923" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a5a39d3b47aa0dc28121635f14" ON "interactive_entity" ("kind") `);
        await queryRunner.query(`CREATE TYPE "public"."non_interactive_entity_kind_enum" AS ENUM('wall', 'pillar', 'tree', 'off_map')`);
        await queryRunner.query(`CREATE TABLE "non_interactive_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "kind" "public"."non_interactive_entity_kind_enum" NOT NULL, "is_visible" boolean NOT NULL, "is_blocking" boolean NOT NULL, "can_interact" boolean NOT NULL, "tile_id" uuid NOT NULL, CONSTRAINT "PK_3692ec6ae8736326a2214952029" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "bounding_box" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "room_id" uuid NOT NULL, "top_left_row" integer NOT NULL, "top_left_column" integer NOT NULL, "bottom_right_row" integer NOT NULL, "bottom_right_column" integer NOT NULL, CONSTRAINT "PK_c8a5a948f17895e18dbb5512ced" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "room" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "has_been_visited" boolean NOT NULL, CONSTRAINT "PK_c6d46db005d623e691b2fbcba23" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "is_starting_tile" boolean NOT NULL, "board_id" uuid NOT NULL, "room_id" uuid NOT NULL, "coord_row" integer NOT NULL, "coord_column" integer NOT NULL, CONSTRAINT "UQ_5153977d63d1d77b908e654bb8f" UNIQUE ("coord_column", "coord_row", "board_id"), CONSTRAINT "PK_b5bf4fc6593cc524004043a6f8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."inventory_item_storage_space_enum" AS ENUM('gear', 'backpack')`);
        await queryRunner.query(`CREATE TABLE "inventory_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "storage_space" "public"."inventory_item_storage_space_enum" NOT NULL, "item_name" character varying NOT NULL, "inventory_id" uuid NOT NULL, CONSTRAINT "PK_94f5cbcb5f280f2f30bd4a9fd90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "inventory" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "storage_capacity_nb_artifact_slots" integer NOT NULL, "storage_capacity_nb_spell_slots" integer NOT NULL, "storage_capacity_nb_weapon_slots" integer NOT NULL, "storage_capacity_nb_backpack_slots" integer NOT NULL, CONSTRAINT "PK_82aa5da437c5bbfb80703b08309" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."playable_entity_faction_enum" AS ENUM('hero', 'monster')`);
        await queryRunner.query(`CREATE TYPE "public"."playable_entity_archetype_enum" AS ENUM('humanoid', 'gobelinoid', 'undead')`);
        await queryRunner.query(`CREATE TYPE "public"."playable_entity_race_enum" AS ENUM('goblin', 'bugbear', 'human', 'elf', 'halfling')`);
        await queryRunner.query(`CREATE TYPE "public"."playable_entity_current_phase_enum" AS ENUM('preparation', 'idle', 'action')`);
        await queryRunner.query(`CREATE TYPE "public"."playable_entity_class_enum" AS ENUM('WARRIOR', 'CLERIC', 'SORCERER', 'THIEF')`);
        await queryRunner.query(`CREATE TABLE "playable_entity" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "faction" "public"."playable_entity_faction_enum" NOT NULL, "archetype" "public"."playable_entity_archetype_enum" NOT NULL, "race" "public"."playable_entity_race_enum" NOT NULL, "current_phase" "public"."playable_entity_current_phase_enum" NOT NULL, "played_by_user_id" character varying NOT NULL, "name" character varying NOT NULL, "initiative" integer NOT NULL, "is_blocking" boolean NOT NULL, "class" "public"."playable_entity_class_enum", "level" integer, "tile_id" uuid NOT NULL, "game_progression_id" uuid NOT NULL, "coord_row" integer, "coord_column" integer, "base_characteristic_health_points" integer, "base_characteristic_mana_points" integer, "base_characteristic_armor_class" integer, "base_characteristic_movement_points" integer, "base_characteristic_action_points" integer, "characteristic_health_points" integer, "characteristic_mana_points" integer, "characteristic_armor_class" integer, "characteristic_movement_points" integer, "characteristic_action_points" integer, CONSTRAINT "PK_3856c3706a79fecf26f280f5fdf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."action_history_name_enum" AS ENUM('attack', 'move', 'open_door', 'delete_item', 'swap_items', 'open_chest')`);
        await queryRunner.query(`CREATE TABLE "action_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."action_history_name_enum" NOT NULL, "playable_entity_id" uuid NOT NULL, CONSTRAINT "PK_ca1fdf2edcf542ad46702522633" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "game_progression" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" character varying NOT NULL, "campaign_id" character varying NOT NULL, CONSTRAINT "UQ_f3283f31e97929c602ce1ba99c9" UNIQUE ("user_id", "campaign_id"), CONSTRAINT "PK_640d42cd4a981f62494c9ae0184" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "campaign_stage_eligibility" ("campaign_stage_id" uuid NOT NULL DEFAULT uuid_generate_v4(), CONSTRAINT "PK_b37776776c21d71912030341c54" PRIMARY KEY ("campaign_stage_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."hero_template_race_enum" AS ENUM('goblin', 'bugbear', 'human', 'elf', 'halfling')`);
        await queryRunner.query(`CREATE TYPE "public"."hero_template_archetype_enum" AS ENUM('humanoid', 'gobelinoid', 'undead')`);
        await queryRunner.query(`CREATE TYPE "public"."hero_template_class_enum" AS ENUM('WARRIOR', 'CLERIC', 'SORCERER', 'THIEF')`);
        await queryRunner.query(`CREATE TABLE "hero_template" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "race" "public"."hero_template_race_enum" NOT NULL, "archetype" "public"."hero_template_archetype_enum" NOT NULL, "name" character varying NOT NULL, "class" "public"."hero_template_class_enum" NOT NULL, "level" integer NOT NULL, "characteristic_health_points" integer NOT NULL, "characteristic_mana_points" integer NOT NULL, "characteristic_armor_class" integer NOT NULL, "characteristic_movement_points" integer NOT NULL, "characteristic_action_points" integer NOT NULL, CONSTRAINT "UQ_c0cdd01a4b917867ad0dfcd2bc8" UNIQUE ("name", "class", "level"), CONSTRAINT "PK_f0b33c71b382a5508a7c213c2c0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "hero_template_ui" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "img_url" character varying NOT NULL, "playable_entity_template_id" uuid, CONSTRAINT "PK_b238b9779f95e27d899f428f5af" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."monster_template_race_enum" AS ENUM('goblin', 'bugbear', 'human', 'elf', 'halfling')`);
        await queryRunner.query(`CREATE TYPE "public"."monster_template_archetype_enum" AS ENUM('humanoid', 'gobelinoid', 'undead')`);
        await queryRunner.query(`CREATE TABLE "monster_template" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "race" "public"."monster_template_race_enum" NOT NULL, "archetype" "public"."monster_template_archetype_enum" NOT NULL, "characteristic_health_points" integer NOT NULL, "characteristic_mana_points" integer NOT NULL, "characteristic_armor_class" integer NOT NULL, "characteristic_movement_points" integer NOT NULL, "characteristic_action_points" integer NOT NULL, CONSTRAINT "PK_000dca08b7b0d224bdb497c321d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "monster_template_ui" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "img_url" character varying NOT NULL, "playable_entity_template_id" uuid, CONSTRAINT "PK_2ab1f5a38fabe1fc58a970b2a6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "spell_attack_dice_throw" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "dice_name" character varying NOT NULL, "cause_id" uuid NOT NULL, CONSTRAINT "PK_95228d60c21e9ce4f2c33f11341" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."mana_cost_class_enum" AS ENUM('CLERIC', 'SORCERER')`);
        await queryRunner.query(`CREATE TABLE "mana_cost" ("id" character varying NOT NULL, "class" "public"."mana_cost_class_enum" NOT NULL, "cost" integer NOT NULL, CONSTRAINT "UQ_9e196ba5b052a4973128e0826c2" UNIQUE ("class", "cost"), CONSTRAINT "PK_d0bc728d82e2b4d9fd97edee0ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."spell_attack_range_enum" AS ENUM('melee', 'long', 'versatile')`);
        await queryRunner.query(`CREATE TYPE "public"."spell_attack_type_enum" AS ENUM('regular', 'super')`);
        await queryRunner.query(`CREATE TABLE "spell_attack" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "range" "public"."spell_attack_range_enum" NOT NULL, "type" "public"."spell_attack_type_enum" NOT NULL, "attack_item_name" character varying, CONSTRAINT "PK_4728477083fd04a98b280a0254c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "weapon_attack_dice_throw" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "dice_name" character varying NOT NULL, "cause_id" uuid NOT NULL, CONSTRAINT "PK_7329be405cc27a3fd0eac1d70ba" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."weapon_attack_range_enum" AS ENUM('melee', 'long', 'versatile')`);
        await queryRunner.query(`CREATE TYPE "public"."weapon_attack_type_enum" AS ENUM('regular', 'super')`);
        await queryRunner.query(`CREATE TABLE "weapon_attack" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "range" "public"."weapon_attack_range_enum" NOT NULL, "type" "public"."weapon_attack_type_enum" NOT NULL, "attack_item_name" character varying, CONSTRAINT "PK_cbce94562a78d3842a0caeb5a67" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "item_ui" ("item_name" character varying NOT NULL, "img_url" character varying NOT NULL, CONSTRAINT "PK_989b338253ff5d42969d3fbb2b6" PRIMARY KEY ("item_name"))`);
        await queryRunner.query(`CREATE TABLE "monster_killed" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_date" TIMESTAMP NOT NULL DEFAULT now(), "monster_template_id" uuid, "killer_id" uuid, "room_id" uuid, CONSTRAINT "PK_01b43b3ebb236705b86ce4578e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."playable_character_type_enum" AS ENUM('game_master', 'hero')`);
        await queryRunner.query(`CREATE TABLE "playable_character" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" "public"."playable_character_type_enum" NOT NULL, "picked_by_user_id" character varying, "lobby_id" uuid NOT NULL, CONSTRAINT "UQ_2421443c097a5575476ac989522" UNIQUE ("name", "lobby_id"), CONSTRAINT "PK_7328d52067665b346f2e7e8122a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."lobby_status_enum" AS ENUM('OPENED', 'GAME_INITIALIZING', 'GAME_STARTED')`);
        await queryRunner.query(`CREATE TABLE "lobby" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "status" "public"."lobby_status_enum" NOT NULL, "host_player_user_id" character varying, "config_nb_players_max" integer NOT NULL, "config_campaign_id" character varying NOT NULL, "config_campaign_nb_stages" integer NOT NULL, "config_campaign_stage_id" character varying NOT NULL, "config_campaign_stage_order" integer NOT NULL, CONSTRAINT "REL_ca414b96153a3814cf6572666b" UNIQUE ("host_player_user_id"), CONSTRAINT "PK_0d9e681a820740df03d4ba784bd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "player" ("user_id" character varying NOT NULL, "is_ready" boolean NOT NULL, "lobby_id" uuid NOT NULL, CONSTRAINT "PK_d04e64fc9b7fd372000c0dfda3f" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE TABLE "translation" ("locale" character varying NOT NULL, "namespace" character varying NOT NULL, "translations" json NOT NULL DEFAULT '{}', CONSTRAINT "PK_a148dc2c7fd9f76e2ac1e4f7556" PRIMARY KEY ("locale", "namespace"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_status_enum" AS ENUM('CREATED', 'INITIALIZED')`);
        await queryRunner.query(`CREATE TABLE "user" ("id" character varying NOT NULL, "status" "public"."user_status_enum" NOT NULL, "avatar_url" character varying NOT NULL, "username" character varying NOT NULL, CONSTRAINT "PK_cace4a159ff9f2512dd42373760" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "item_item_perks_item_perk" ("item_name" character varying NOT NULL, "item_perk_id" uuid NOT NULL, CONSTRAINT "PK_185b4e2f8d9a54de64705b8f2de" PRIMARY KEY ("item_name", "item_perk_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_32626954faf6de7764f7f0af7f" ON "item_item_perks_item_perk" ("item_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_7b8abc7f28b3fe6d79dbe87a4f" ON "item_item_perks_item_perk" ("item_perk_id") `);
        await queryRunner.query(`CREATE TABLE "item_mana_costs_mana_cost" ("item_name" character varying NOT NULL, "mana_cost_id" character varying NOT NULL, CONSTRAINT "PK_094455173fb73c40c061a520c03" PRIMARY KEY ("item_name", "mana_cost_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_751969901ef10ee1805b261593" ON "item_mana_costs_mana_cost" ("item_name") `);
        await queryRunner.query(`CREATE INDEX "IDX_46349911e0fd3bdd17aa5c52aa" ON "item_mana_costs_mana_cost" ("mana_cost_id") `);
        await queryRunner.query(`CREATE TABLE "game_items_looted_item" ("game_id" uuid NOT NULL, "item_name" character varying NOT NULL, CONSTRAINT "PK_7978b1ad787837803b9ac82010c" PRIMARY KEY ("game_id", "item_name"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d81bd5895c3df8ddebe5eb723b" ON "game_items_looted_item" ("game_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7ba3924474c9db1d09d7cddf7" ON "game_items_looted_item" ("item_name") `);
        await queryRunner.query(`CREATE TABLE "game_event_monsters_monster_template" ("game_event_id" uuid NOT NULL, "monster_template_id" uuid NOT NULL, CONSTRAINT "PK_61eb6b5d0ade4433109c78affe6" PRIMARY KEY ("game_event_id", "monster_template_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0c3e1f2623a05e5534105d1bb7" ON "game_event_monsters_monster_template" ("game_event_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_66f04abfba71946464dfe6cfd6" ON "game_event_monsters_monster_template" ("monster_template_id") `);
        await queryRunner.query(`CREATE TABLE "game_progression_items_looted_item" ("game_progression_id" uuid NOT NULL, "item_name" character varying NOT NULL, CONSTRAINT "PK_7823fe8accd33608eba09c1bb9c" PRIMARY KEY ("game_progression_id", "item_name"))`);
        await queryRunner.query(`CREATE INDEX "IDX_7800342ee82e5bd5f4a58e9a59" ON "game_progression_items_looted_item" ("game_progression_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_33a29d85fe5b7c4d987bcdb8df" ON "game_progression_items_looted_item" ("item_name") `);
        await queryRunner.query(`CREATE TABLE "hero_template_campaign_stage_campaign_stage_eligibility" ("hero_template_id" uuid NOT NULL, "campaign_stage_eligibility_campaign_stage_id" uuid NOT NULL, CONSTRAINT "PK_b5a1f71ae9ba4495177c028be9b" PRIMARY KEY ("hero_template_id", "campaign_stage_eligibility_campaign_stage_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cd5cbf59a4c9a8548293526440" ON "hero_template_campaign_stage_campaign_stage_eligibility" ("hero_template_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3c2870e006ea2e3eeb0a251720" ON "hero_template_campaign_stage_campaign_stage_eligibility" ("campaign_stage_eligibility_campaign_stage_id") `);
        await queryRunner.query(`CREATE TABLE "spell_attack_perks_perk" ("spell_attack_id" uuid NOT NULL, "perk_name" character varying NOT NULL, CONSTRAINT "PK_fa5d88537ee8f08096824b051ea" PRIMARY KEY ("spell_attack_id", "perk_name"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8c9ffe32d515f6f776509a8233" ON "spell_attack_perks_perk" ("spell_attack_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1cefab2f9fb8ab817b8345c05e" ON "spell_attack_perks_perk" ("perk_name") `);
        await queryRunner.query(`CREATE TABLE "weapon_attack_perks_perk" ("weapon_attack_id" uuid NOT NULL, "perk_name" character varying NOT NULL, CONSTRAINT "PK_b3414bb959dad2489c8bbad19f8" PRIMARY KEY ("weapon_attack_id", "perk_name"))`);
        await queryRunner.query(`CREATE INDEX "IDX_077d151c6fea28f996f7e1ef99" ON "weapon_attack_perks_perk" ("weapon_attack_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_87183c48955f0d3d1d3cfc8593" ON "weapon_attack_perks_perk" ("perk_name") `);
        await queryRunner.query(`ALTER TABLE "campaign_stage" ADD CONSTRAINT "FK_f75ced37a3d6831637a18e340a6" FOREIGN KEY ("campaign_id") REFERENCES "campaign"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaign_stage_progression" ADD CONSTRAINT "FK_6123bbfcc578ef5c1e4a594d252" FOREIGN KEY ("campaign_progression_id") REFERENCES "campaign_progression"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaign_stage_progression" ADD CONSTRAINT "FK_554ee9f8ace927ca79f9a0b582b" FOREIGN KEY ("stage_id") REFERENCES "campaign_stage"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "campaign_progression" ADD CONSTRAINT "FK_b623a64b8dc76dc6d8d7a72aeab" FOREIGN KEY ("campaign_id") REFERENCES "campaign"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playable_entity_condition" ADD CONSTRAINT "FK_bfb3aee60796445928f6b577386" FOREIGN KEY ("playable_entity_id") REFERENCES "playable_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "current_game_event" ADD CONSTRAINT "FK_a28a39aa1e640e52f756865a84b" FOREIGN KEY ("game_id") REFERENCES "game"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "current_game_event" ADD CONSTRAINT "FK_40c5061dda07f5b026d7c2c99e1" FOREIGN KEY ("game_event_id") REFERENCES "game_event"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_perk_dice_throw" ADD CONSTRAINT "FK_27a60e3c142fe8c21fd171eefb9" FOREIGN KEY ("dice_name") REFERENCES "dice"("name") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_perk_dice_throw" ADD CONSTRAINT "FK_e2836c3bfa1006f007dce32625f" FOREIGN KEY ("cause_id") REFERENCES "item_perk"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_perk" ADD CONSTRAINT "FK_d3f43c7580e44268940b15ec5b2" FOREIGN KEY ("perk_name") REFERENCES "perk"("name") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "win_condition" ADD CONSTRAINT "FK_a89c63083753dc452656056a453" FOREIGN KEY ("game_id") REFERENCES "game"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game" ADD CONSTRAINT "FK_0152ef021e5a686c048f756ebd3" FOREIGN KEY ("board_id") REFERENCES "board"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_event" ADD CONSTRAINT "FK_c0d920bcadc48f68e040d756a99" FOREIGN KEY ("game_id") REFERENCES "game"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_event" ADD CONSTRAINT "FK_426f6d808d701deb57f05b03a63" FOREIGN KEY ("starting_room_id") REFERENCES "room"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "game_template" ADD CONSTRAINT "FK_a5713d51eb46a0faacea0236a05" FOREIGN KEY ("board_id") REFERENCES "board"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "interactive_entity" ADD CONSTRAINT "FK_68e176785ac02e48e57e64e5735" FOREIGN KEY ("tile_id") REFERENCES "tile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "non_interactive_entity" ADD CONSTRAINT "FK_0732a3560cf6a3d4fbc366af8e1" FOREIGN KEY ("tile_id") REFERENCES "tile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bounding_box" ADD CONSTRAINT "FK_272447b60f1786e57e5eb093628" FOREIGN KEY ("room_id") REFERENCES "room"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tile" ADD CONSTRAINT "FK_8132a17896d6b83e0dddb7b1dd9" FOREIGN KEY ("board_id") REFERENCES "board"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tile" ADD CONSTRAINT "FK_90f242b2846e44aa14f3d05119a" FOREIGN KEY ("room_id") REFERENCES "room"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_18514452122f8d877fbbec108fd" FOREIGN KEY ("item_name") REFERENCES "item"("name") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_item" ADD CONSTRAINT "FK_a2129b235bd560a0a725ae3404b" FOREIGN KEY ("inventory_id") REFERENCES "inventory"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playable_entity" ADD CONSTRAINT "FK_8b8c2a38adc47c9eda2ac9e213a" FOREIGN KEY ("tile_id") REFERENCES "tile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playable_entity" ADD CONSTRAINT "FK_927e965d92e8baf45265459572e" FOREIGN KEY ("game_progression_id") REFERENCES "game_progression"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "action_history" ADD CONSTRAINT "FK_3f76d8b25c18acd758f77ee4660" FOREIGN KEY ("playable_entity_id") REFERENCES "playable_entity"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "hero_template_ui" ADD CONSTRAINT "FK_47cc5592a9ee73271dc9da31a10" FOREIGN KEY ("playable_entity_template_id") REFERENCES "hero_template"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "monster_template_ui" ADD CONSTRAINT "FK_c47f261c91979d8bfaaee27a84c" FOREIGN KEY ("playable_entity_template_id") REFERENCES "monster_template"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spell_attack_dice_throw" ADD CONSTRAINT "FK_bd85799f2629c4aa3662487cb7b" FOREIGN KEY ("dice_name") REFERENCES "dice"("name") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spell_attack_dice_throw" ADD CONSTRAINT "FK_26ff46632d0263dc0d45c328fb7" FOREIGN KEY ("cause_id") REFERENCES "spell_attack"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "spell_attack" ADD CONSTRAINT "FK_a85280dcd69976ec27e666b6032" FOREIGN KEY ("attack_item_name") REFERENCES "item"("name") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weapon_attack_dice_throw" ADD CONSTRAINT "FK_045fe30d823da751923bd071887" FOREIGN KEY ("dice_name") REFERENCES "dice"("name") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weapon_attack_dice_throw" ADD CONSTRAINT "FK_034bafcb28ccb3285254ca06b24" FOREIGN KEY ("cause_id") REFERENCES "weapon_attack"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weapon_attack" ADD CONSTRAINT "FK_3855fceb23cdc1b08220c098fb6" FOREIGN KEY ("attack_item_name") REFERENCES "item"("name") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_ui" ADD CONSTRAINT "FK_989b338253ff5d42969d3fbb2b6" FOREIGN KEY ("item_name") REFERENCES "item"("name") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "monster_killed" ADD CONSTRAINT "FK_83ebfe4b0079c3c82a46a2daea7" FOREIGN KEY ("monster_template_id") REFERENCES "monster_template"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "monster_killed" ADD CONSTRAINT "FK_bc0f2c3a413888dc99483dfa467" FOREIGN KEY ("killer_id") REFERENCES "playable_entity"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "monster_killed" ADD CONSTRAINT "FK_5137c5caeb5a1a7aa011b0f0b40" FOREIGN KEY ("room_id") REFERENCES "room"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playable_character" ADD CONSTRAINT "FK_2fcff8d86c07baa95f82a46dce0" FOREIGN KEY ("picked_by_user_id") REFERENCES "player"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "playable_character" ADD CONSTRAINT "FK_53962aaea6d2e0ae0b81f81c6ea" FOREIGN KEY ("lobby_id") REFERENCES "lobby"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lobby" ADD CONSTRAINT "FK_ca414b96153a3814cf6572666bd" FOREIGN KEY ("host_player_user_id") REFERENCES "player"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "player" ADD CONSTRAINT "FK_0eb89d7ed5f08885d3e921d03e5" FOREIGN KEY ("lobby_id") REFERENCES "lobby"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "item_item_perks_item_perk" ADD CONSTRAINT "FK_32626954faf6de7764f7f0af7fb" FOREIGN KEY ("item_name") REFERENCES "item"("name") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "item_item_perks_item_perk" ADD CONSTRAINT "FK_7b8abc7f28b3fe6d79dbe87a4f1" FOREIGN KEY ("item_perk_id") REFERENCES "item_perk"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "item_mana_costs_mana_cost" ADD CONSTRAINT "FK_751969901ef10ee1805b2615932" FOREIGN KEY ("item_name") REFERENCES "item"("name") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "item_mana_costs_mana_cost" ADD CONSTRAINT "FK_46349911e0fd3bdd17aa5c52aa8" FOREIGN KEY ("mana_cost_id") REFERENCES "mana_cost"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "game_items_looted_item" ADD CONSTRAINT "FK_d81bd5895c3df8ddebe5eb723b8" FOREIGN KEY ("game_id") REFERENCES "game"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "game_items_looted_item" ADD CONSTRAINT "FK_e7ba3924474c9db1d09d7cddf78" FOREIGN KEY ("item_name") REFERENCES "item"("name") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "game_event_monsters_monster_template" ADD CONSTRAINT "FK_0c3e1f2623a05e5534105d1bb72" FOREIGN KEY ("game_event_id") REFERENCES "game_event"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "game_event_monsters_monster_template" ADD CONSTRAINT "FK_66f04abfba71946464dfe6cfd6c" FOREIGN KEY ("monster_template_id") REFERENCES "monster_template"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "game_progression_items_looted_item" ADD CONSTRAINT "FK_7800342ee82e5bd5f4a58e9a594" FOREIGN KEY ("game_progression_id") REFERENCES "game_progression"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "game_progression_items_looted_item" ADD CONSTRAINT "FK_33a29d85fe5b7c4d987bcdb8dfc" FOREIGN KEY ("item_name") REFERENCES "item"("name") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "hero_template_campaign_stage_campaign_stage_eligibility" ADD CONSTRAINT "FK_cd5cbf59a4c9a85482935264400" FOREIGN KEY ("hero_template_id") REFERENCES "hero_template"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "hero_template_campaign_stage_campaign_stage_eligibility" ADD CONSTRAINT "FK_3c2870e006ea2e3eeb0a2517203" FOREIGN KEY ("campaign_stage_eligibility_campaign_stage_id") REFERENCES "campaign_stage_eligibility"("campaign_stage_id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "spell_attack_perks_perk" ADD CONSTRAINT "FK_8c9ffe32d515f6f776509a8233e" FOREIGN KEY ("spell_attack_id") REFERENCES "spell_attack"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "spell_attack_perks_perk" ADD CONSTRAINT "FK_1cefab2f9fb8ab817b8345c05e3" FOREIGN KEY ("perk_name") REFERENCES "perk"("name") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "weapon_attack_perks_perk" ADD CONSTRAINT "FK_077d151c6fea28f996f7e1ef99f" FOREIGN KEY ("weapon_attack_id") REFERENCES "weapon_attack"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "weapon_attack_perks_perk" ADD CONSTRAINT "FK_87183c48955f0d3d1d3cfc8593e" FOREIGN KEY ("perk_name") REFERENCES "perk"("name") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "weapon_attack_perks_perk" DROP CONSTRAINT "FK_87183c48955f0d3d1d3cfc8593e"`);
        await queryRunner.query(`ALTER TABLE "weapon_attack_perks_perk" DROP CONSTRAINT "FK_077d151c6fea28f996f7e1ef99f"`);
        await queryRunner.query(`ALTER TABLE "spell_attack_perks_perk" DROP CONSTRAINT "FK_1cefab2f9fb8ab817b8345c05e3"`);
        await queryRunner.query(`ALTER TABLE "spell_attack_perks_perk" DROP CONSTRAINT "FK_8c9ffe32d515f6f776509a8233e"`);
        await queryRunner.query(`ALTER TABLE "hero_template_campaign_stage_campaign_stage_eligibility" DROP CONSTRAINT "FK_3c2870e006ea2e3eeb0a2517203"`);
        await queryRunner.query(`ALTER TABLE "hero_template_campaign_stage_campaign_stage_eligibility" DROP CONSTRAINT "FK_cd5cbf59a4c9a85482935264400"`);
        await queryRunner.query(`ALTER TABLE "game_progression_items_looted_item" DROP CONSTRAINT "FK_33a29d85fe5b7c4d987bcdb8dfc"`);
        await queryRunner.query(`ALTER TABLE "game_progression_items_looted_item" DROP CONSTRAINT "FK_7800342ee82e5bd5f4a58e9a594"`);
        await queryRunner.query(`ALTER TABLE "game_event_monsters_monster_template" DROP CONSTRAINT "FK_66f04abfba71946464dfe6cfd6c"`);
        await queryRunner.query(`ALTER TABLE "game_event_monsters_monster_template" DROP CONSTRAINT "FK_0c3e1f2623a05e5534105d1bb72"`);
        await queryRunner.query(`ALTER TABLE "game_items_looted_item" DROP CONSTRAINT "FK_e7ba3924474c9db1d09d7cddf78"`);
        await queryRunner.query(`ALTER TABLE "game_items_looted_item" DROP CONSTRAINT "FK_d81bd5895c3df8ddebe5eb723b8"`);
        await queryRunner.query(`ALTER TABLE "item_mana_costs_mana_cost" DROP CONSTRAINT "FK_46349911e0fd3bdd17aa5c52aa8"`);
        await queryRunner.query(`ALTER TABLE "item_mana_costs_mana_cost" DROP CONSTRAINT "FK_751969901ef10ee1805b2615932"`);
        await queryRunner.query(`ALTER TABLE "item_item_perks_item_perk" DROP CONSTRAINT "FK_7b8abc7f28b3fe6d79dbe87a4f1"`);
        await queryRunner.query(`ALTER TABLE "item_item_perks_item_perk" DROP CONSTRAINT "FK_32626954faf6de7764f7f0af7fb"`);
        await queryRunner.query(`ALTER TABLE "player" DROP CONSTRAINT "FK_0eb89d7ed5f08885d3e921d03e5"`);
        await queryRunner.query(`ALTER TABLE "lobby" DROP CONSTRAINT "FK_ca414b96153a3814cf6572666bd"`);
        await queryRunner.query(`ALTER TABLE "playable_character" DROP CONSTRAINT "FK_53962aaea6d2e0ae0b81f81c6ea"`);
        await queryRunner.query(`ALTER TABLE "playable_character" DROP CONSTRAINT "FK_2fcff8d86c07baa95f82a46dce0"`);
        await queryRunner.query(`ALTER TABLE "monster_killed" DROP CONSTRAINT "FK_5137c5caeb5a1a7aa011b0f0b40"`);
        await queryRunner.query(`ALTER TABLE "monster_killed" DROP CONSTRAINT "FK_bc0f2c3a413888dc99483dfa467"`);
        await queryRunner.query(`ALTER TABLE "monster_killed" DROP CONSTRAINT "FK_83ebfe4b0079c3c82a46a2daea7"`);
        await queryRunner.query(`ALTER TABLE "item_ui" DROP CONSTRAINT "FK_989b338253ff5d42969d3fbb2b6"`);
        await queryRunner.query(`ALTER TABLE "weapon_attack" DROP CONSTRAINT "FK_3855fceb23cdc1b08220c098fb6"`);
        await queryRunner.query(`ALTER TABLE "weapon_attack_dice_throw" DROP CONSTRAINT "FK_034bafcb28ccb3285254ca06b24"`);
        await queryRunner.query(`ALTER TABLE "weapon_attack_dice_throw" DROP CONSTRAINT "FK_045fe30d823da751923bd071887"`);
        await queryRunner.query(`ALTER TABLE "spell_attack" DROP CONSTRAINT "FK_a85280dcd69976ec27e666b6032"`);
        await queryRunner.query(`ALTER TABLE "spell_attack_dice_throw" DROP CONSTRAINT "FK_26ff46632d0263dc0d45c328fb7"`);
        await queryRunner.query(`ALTER TABLE "spell_attack_dice_throw" DROP CONSTRAINT "FK_bd85799f2629c4aa3662487cb7b"`);
        await queryRunner.query(`ALTER TABLE "monster_template_ui" DROP CONSTRAINT "FK_c47f261c91979d8bfaaee27a84c"`);
        await queryRunner.query(`ALTER TABLE "hero_template_ui" DROP CONSTRAINT "FK_47cc5592a9ee73271dc9da31a10"`);
        await queryRunner.query(`ALTER TABLE "action_history" DROP CONSTRAINT "FK_3f76d8b25c18acd758f77ee4660"`);
        await queryRunner.query(`ALTER TABLE "playable_entity" DROP CONSTRAINT "FK_927e965d92e8baf45265459572e"`);
        await queryRunner.query(`ALTER TABLE "playable_entity" DROP CONSTRAINT "FK_8b8c2a38adc47c9eda2ac9e213a"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_a2129b235bd560a0a725ae3404b"`);
        await queryRunner.query(`ALTER TABLE "inventory_item" DROP CONSTRAINT "FK_18514452122f8d877fbbec108fd"`);
        await queryRunner.query(`ALTER TABLE "tile" DROP CONSTRAINT "FK_90f242b2846e44aa14f3d05119a"`);
        await queryRunner.query(`ALTER TABLE "tile" DROP CONSTRAINT "FK_8132a17896d6b83e0dddb7b1dd9"`);
        await queryRunner.query(`ALTER TABLE "bounding_box" DROP CONSTRAINT "FK_272447b60f1786e57e5eb093628"`);
        await queryRunner.query(`ALTER TABLE "non_interactive_entity" DROP CONSTRAINT "FK_0732a3560cf6a3d4fbc366af8e1"`);
        await queryRunner.query(`ALTER TABLE "interactive_entity" DROP CONSTRAINT "FK_68e176785ac02e48e57e64e5735"`);
        await queryRunner.query(`ALTER TABLE "game_template" DROP CONSTRAINT "FK_a5713d51eb46a0faacea0236a05"`);
        await queryRunner.query(`ALTER TABLE "game_event" DROP CONSTRAINT "FK_426f6d808d701deb57f05b03a63"`);
        await queryRunner.query(`ALTER TABLE "game_event" DROP CONSTRAINT "FK_c0d920bcadc48f68e040d756a99"`);
        await queryRunner.query(`ALTER TABLE "game" DROP CONSTRAINT "FK_0152ef021e5a686c048f756ebd3"`);
        await queryRunner.query(`ALTER TABLE "win_condition" DROP CONSTRAINT "FK_a89c63083753dc452656056a453"`);
        await queryRunner.query(`ALTER TABLE "item_perk" DROP CONSTRAINT "FK_d3f43c7580e44268940b15ec5b2"`);
        await queryRunner.query(`ALTER TABLE "item_perk_dice_throw" DROP CONSTRAINT "FK_e2836c3bfa1006f007dce32625f"`);
        await queryRunner.query(`ALTER TABLE "item_perk_dice_throw" DROP CONSTRAINT "FK_27a60e3c142fe8c21fd171eefb9"`);
        await queryRunner.query(`ALTER TABLE "current_game_event" DROP CONSTRAINT "FK_40c5061dda07f5b026d7c2c99e1"`);
        await queryRunner.query(`ALTER TABLE "current_game_event" DROP CONSTRAINT "FK_a28a39aa1e640e52f756865a84b"`);
        await queryRunner.query(`ALTER TABLE "playable_entity_condition" DROP CONSTRAINT "FK_bfb3aee60796445928f6b577386"`);
        await queryRunner.query(`ALTER TABLE "campaign_progression" DROP CONSTRAINT "FK_b623a64b8dc76dc6d8d7a72aeab"`);
        await queryRunner.query(`ALTER TABLE "campaign_stage_progression" DROP CONSTRAINT "FK_554ee9f8ace927ca79f9a0b582b"`);
        await queryRunner.query(`ALTER TABLE "campaign_stage_progression" DROP CONSTRAINT "FK_6123bbfcc578ef5c1e4a594d252"`);
        await queryRunner.query(`ALTER TABLE "campaign_stage" DROP CONSTRAINT "FK_f75ced37a3d6831637a18e340a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87183c48955f0d3d1d3cfc8593"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_077d151c6fea28f996f7e1ef99"`);
        await queryRunner.query(`DROP TABLE "weapon_attack_perks_perk"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cefab2f9fb8ab817b8345c05e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c9ffe32d515f6f776509a8233"`);
        await queryRunner.query(`DROP TABLE "spell_attack_perks_perk"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3c2870e006ea2e3eeb0a251720"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cd5cbf59a4c9a8548293526440"`);
        await queryRunner.query(`DROP TABLE "hero_template_campaign_stage_campaign_stage_eligibility"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_33a29d85fe5b7c4d987bcdb8df"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7800342ee82e5bd5f4a58e9a59"`);
        await queryRunner.query(`DROP TABLE "game_progression_items_looted_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66f04abfba71946464dfe6cfd6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0c3e1f2623a05e5534105d1bb7"`);
        await queryRunner.query(`DROP TABLE "game_event_monsters_monster_template"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7ba3924474c9db1d09d7cddf7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d81bd5895c3df8ddebe5eb723b"`);
        await queryRunner.query(`DROP TABLE "game_items_looted_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46349911e0fd3bdd17aa5c52aa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_751969901ef10ee1805b261593"`);
        await queryRunner.query(`DROP TABLE "item_mana_costs_mana_cost"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7b8abc7f28b3fe6d79dbe87a4f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32626954faf6de7764f7f0af7f"`);
        await queryRunner.query(`DROP TABLE "item_item_perks_item_perk"`);
        await queryRunner.query(`DROP TABLE "user"`);
        await queryRunner.query(`DROP TYPE "public"."user_status_enum"`);
        await queryRunner.query(`DROP TABLE "translation"`);
        await queryRunner.query(`DROP TABLE "player"`);
        await queryRunner.query(`DROP TABLE "lobby"`);
        await queryRunner.query(`DROP TYPE "public"."lobby_status_enum"`);
        await queryRunner.query(`DROP TABLE "playable_character"`);
        await queryRunner.query(`DROP TYPE "public"."playable_character_type_enum"`);
        await queryRunner.query(`DROP TABLE "monster_killed"`);
        await queryRunner.query(`DROP TABLE "item_ui"`);
        await queryRunner.query(`DROP TABLE "weapon_attack"`);
        await queryRunner.query(`DROP TYPE "public"."weapon_attack_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."weapon_attack_range_enum"`);
        await queryRunner.query(`DROP TABLE "weapon_attack_dice_throw"`);
        await queryRunner.query(`DROP TABLE "spell_attack"`);
        await queryRunner.query(`DROP TYPE "public"."spell_attack_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."spell_attack_range_enum"`);
        await queryRunner.query(`DROP TABLE "mana_cost"`);
        await queryRunner.query(`DROP TYPE "public"."mana_cost_class_enum"`);
        await queryRunner.query(`DROP TABLE "spell_attack_dice_throw"`);
        await queryRunner.query(`DROP TABLE "monster_template_ui"`);
        await queryRunner.query(`DROP TABLE "monster_template"`);
        await queryRunner.query(`DROP TYPE "public"."monster_template_archetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."monster_template_race_enum"`);
        await queryRunner.query(`DROP TABLE "hero_template_ui"`);
        await queryRunner.query(`DROP TABLE "hero_template"`);
        await queryRunner.query(`DROP TYPE "public"."hero_template_class_enum"`);
        await queryRunner.query(`DROP TYPE "public"."hero_template_archetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."hero_template_race_enum"`);
        await queryRunner.query(`DROP TABLE "campaign_stage_eligibility"`);
        await queryRunner.query(`DROP TABLE "game_progression"`);
        await queryRunner.query(`DROP TABLE "action_history"`);
        await queryRunner.query(`DROP TYPE "public"."action_history_name_enum"`);
        await queryRunner.query(`DROP TABLE "playable_entity"`);
        await queryRunner.query(`DROP TYPE "public"."playable_entity_class_enum"`);
        await queryRunner.query(`DROP TYPE "public"."playable_entity_current_phase_enum"`);
        await queryRunner.query(`DROP TYPE "public"."playable_entity_race_enum"`);
        await queryRunner.query(`DROP TYPE "public"."playable_entity_archetype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."playable_entity_faction_enum"`);
        await queryRunner.query(`DROP TABLE "inventory"`);
        await queryRunner.query(`DROP TABLE "inventory_item"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_item_storage_space_enum"`);
        await queryRunner.query(`DROP TABLE "tile"`);
        await queryRunner.query(`DROP TABLE "room"`);
        await queryRunner.query(`DROP TABLE "bounding_box"`);
        await queryRunner.query(`DROP TABLE "non_interactive_entity"`);
        await queryRunner.query(`DROP TYPE "public"."non_interactive_entity_kind_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a5a39d3b47aa0dc28121635f14"`);
        await queryRunner.query(`DROP TABLE "interactive_entity"`);
        await queryRunner.query(`DROP TYPE "public"."interactive_entity_name_enum"`);
        await queryRunner.query(`DROP TYPE "public"."interactive_entity_kind_enum"`);
        await queryRunner.query(`DROP TABLE "board"`);
        await queryRunner.query(`DROP TABLE "game_template"`);
        await queryRunner.query(`DROP TABLE "game_event"`);
        await queryRunner.query(`DROP TYPE "public"."game_event_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."game_event_name_enum"`);
        await queryRunner.query(`DROP TABLE "game"`);
        await queryRunner.query(`DROP TYPE "public"."game_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e32d7130c61d935786cd870b5"`);
        await queryRunner.query(`DROP TABLE "win_condition"`);
        await queryRunner.query(`DROP TYPE "public"."win_condition_name_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6c7fa282dcacbfe6247b28f13"`);
        await queryRunner.query(`DROP TABLE "item"`);
        await queryRunner.query(`DROP TYPE "public"."item_type_enum"`);
        await queryRunner.query(`DROP TABLE "item_perk"`);
        await queryRunner.query(`DROP TABLE "perk"`);
        await queryRunner.query(`DROP TYPE "public"."perk_trigger_enum"`);
        await queryRunner.query(`DROP TABLE "item_perk_dice_throw"`);
        await queryRunner.query(`DROP TABLE "dice"`);
        await queryRunner.query(`DROP TABLE "current_game_event"`);
        await queryRunner.query(`DROP TABLE "playable_entity_condition"`);
        await queryRunner.query(`DROP TYPE "public"."playable_entity_condition_name_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_997e97791ec3aa7af5fb205907"`);
        await queryRunner.query(`DROP TABLE "campaign_progression"`);
        await queryRunner.query(`DROP TYPE "public"."campaign_progression_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da5afe8d6e472dd654037e30c0"`);
        await queryRunner.query(`DROP TABLE "campaign_stage_progression"`);
        await queryRunner.query(`DROP TYPE "public"."campaign_stage_progression_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_090cbf92709adca8d9564daf84"`);
        await queryRunner.query(`DROP TABLE "campaign_stage"`);
        await queryRunner.query(`DROP TYPE "public"."campaign_stage_status_enum"`);
        await queryRunner.query(`DROP TABLE "campaign"`);
        await queryRunner.query(`DROP TYPE "public"."campaign_status_enum"`);
        await queryRunner.query(`DROP TABLE "analytics"`);
    }

}
