INSERT INTO
  enemy_template (
    name,
    characteristic_base_action_points,
    characteristic_base_movement_points,
    characteristic_base_armor_class,
    characteristic_base_mana_points,
    characteristic_base_health_points,
    inventory
  )
VALUES
  (
    'goblin',
    2,
    5,
    1,
    0,
    4,
    '{"gear":[{"type":"weapon","name":"goblin_scimitar_1","level":1,"imgUrl":"","attacks":[{"range":"melee","type":"regular","dices":["yellow","yellow","orange"]}],"perks":[]}],"backpack":[]}'
  ),
  (
    'bugbear',
    2,
    4,
    2,
    0,
    7,
    '{"gear":[{"type":"weapon","name":"bugbear_mace_1","level":1,"imgUrl":"","attacks":[{"range":"melee","type":"regular","dices":["yellow","yellow","red"]}],"perks":[]}],"backpack":[]}'
  );