INSERT INTO
  "item" ("name", "type", "level", "is_lootable_in_chest")
VALUES
  ('broadsword_1', 'Weapon', 1, 'f'),
  ('faith_crossbow_1', 'Weapon', 1, 'f'),
  ('throwing_dagger_1', 'Weapon', 1, 'f'),
  ('elders_shortbow_1', 'Weapon', 1, 'f'),
  ('goblin_scimitar_1', 'Weapon', 1, 'f'),
  ('bugbear_mace_1', 'Weapon', 1, 'f'),
  ('faith_mace_1', 'Weapon', 1, 't'),
  ('master_axe_1', 'Weapon', 1, 't'),
  ('flash_bombs_1', 'Weapon', 1, 't'),
  ('poisoned_blowpipe_1', 'Weapon', 1, 't'),
  ('sword_of_outcast_kings_1', 'Weapon', 1, 't'),
  ('tormented_sword_of_slavery_1', 'Weapon', 1, 't'),
  ('bow_of_freedom_1', 'Weapon', 1, 't'),
  ('elves_blessed_bow_1', 'Weapon', 1, 't'),
  ('trusty_dwarven_forging_axe_1', 'Weapon', 1, 't'),
  ('dragons_fury_1', 'Weapon', 0, 'f'),
  ('kords_unsubmissive_servant_1', 'Weapon', 0, 'f'),
  ('herald_of_pain_1', 'Weapon', 0, 'f'),
  ('two_handed_broadsword_1', 'Weapon', 1, 'f'),
  ('bone_splitter_1', 'Weapon', 1, 't'),
  ('hammer_of_freedom_1', 'Weapon', 1, 't'),
  ('magic_shot_1', 'Spell', 1, 'f'),
  ('pillar_of_fire_1', 'Spell', 0, 'f'),
  ('energy_shield_1', 'Spell', 0, 'f'),
  ('force_cage_1', 'Spell', 1, 't'),
  ('ultimate_restauration_1', 'Spell', 1, 'f'),
  ('invisible_servant_1', 'Spell', 1, 't'),
  ('partial_healing_circle_1', 'Spell', 1, 't'),
  ('ray_of_frost_1', 'Spell', 1, 't'),
  ('melfs_acid_arrow_1', 'Spell', 1, 't'),
  ('flaming_arrows_1', 'Spell', 1, 't'),
  ('burning_hands_1', 'Spell', 1, 't'),
  ('call_from_the_grave_1', 'ChestTrap', 1, 't'),
  ('voices_of_the_damned_1', 'ChestTrap', 1, 't'),
  ('dazzling_light_1', 'ChestTrap', 1, 't'),
  ('smothering_mist_1', 'ChestTrap', 1, 't'),
  ('brutal_betrayal_1', 'ChestTrap', 2, 't'),
  ('magic_loss_1', 'ChestTrap', 3, 't'),
  ('blanket_of_flames_1', 'ChestTrap', 3, 't'),
  ('orb_of_lucid_vision_1', 'Artifact', 0, 'f'),
  ('boccobs_cloak_1', 'Artifact', 0, 'f'),
  ('yonddalla_amulet_1', 'Artifact', 1, 'f'),
  ('ring_of_shadows_1', 'Artifact', 1, 't'),
  ('summoners_horn_1', 'Artifact', 1, 't'),
  ('bark_skin_cloak_1', 'Artifact', 1, 't'),
  ('olidammara_amulet_1', 'Artifact', 1, 't'),
  ('potion_of_weakness_1', 'Potion', 1, 't'),
  ('smoke_shadow_potion_1', 'Potion', 1, 't'),
  ('kords_blessing_potion_1', 'Potion', 1, 't'),
  ('imperious_hand_potion_1', 'Potion', 1, 't'),
  ('potion_of_laughter_1', 'Potion', 1, 't'),
  ('olidammara_wisdom_potion_1', 'Potion', 1, 't'),
  ('partial_restoration_potion_1', 'Potion', 1, 't'),
  ('initiative_potion_1', 'Potion', 1, 't'),
  (
    'ultimate_restoration_potion_1',
    'Potion',
    1,
    't'
  ),
  ('light_healing_potion_1', 'Potion', 1, 't');