INSERT INTO
  "item_ui" ("item_name", "img_url")
VALUES
  (
    'broadsword_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/broadsword_1.webp'
  ),
  (
    'faith_crossbow_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/faith_crossbow_1.webp'
  ),
  (
    'throwing_dagger_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/throwing_dagger_1.webp'
  ),
  (
    'magic_shot_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/magic_shot_1.webp'
  ),
  (
    'elders_shortbow_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/elders_shortbow_1.webp'
  ),
  (
    'goblin_scimitar_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/goblin_scimitar_1.webp'
  ),
  (
    'bugbear_mace_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/bugbear_mace_1.webp'
  ),
  (
    'faith_mace_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/faith_mace_1.webp'
  ),
  (
    'master_axe_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/master_axe_1.webp'
  ),
  (
    'flash_bombs_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/flash_bombs_1.webp'
  ),
  (
    'poisoned_blowpipe_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/poisoned_blowpipe_1.webp'
  ),
  (
    'sword_of_outcast_kings_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/sword_of_outcast_kings_1.webp'
  ),
  (
    'tormented_sword_of_slavery_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/tormented_sword_of_slavery_1.webp'
  ),
  (
    'bow_of_freedom_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/bow_of_freedom_1.webp'
  ),
  (
    'elves_blessed_bow_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/elves_blessed_bow_1.webp'
  ),
  (
    'trusty_dwarven_forging_axe_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/trusty_dwarven_forging_axe_1.webp'
  ),
  (
    'dragons_fury_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/dragons_fury_1.webp'
  ),
  (
    'kords_unsubmissive_servant_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/kords_unsubmissive_servant_1.webp'
  ),
  (
    'herald_of_pain_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/herald_of_pain_1.webp'
  ),
  (
    'two_handed_broadsword_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/two_handed_broadsword_1.webp'
  ),
  (
    'bone_splitter_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/bone_splitter_1.webp'
  ),
  (
    'hammer_of_freedom_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/hammer_of_freedom_1.webp'
  ),
  (
    'pillar_of_fire_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/pillar_of_fire_1.webp'
  ),
  (
    'energy_shield_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/energy_shield_1.webp'
  ),
  (
    'force_cage_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/force_cage_1.webp'
  ),
  (
    'ultimate_restauration_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/ultimate_restauration_1.webp'
  ),
  (
    'invisible_servant_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/invisible_servant_1.webp'
  ),
  (
    'partial_healing_circle_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/partial_healing_circle_1.webp'
  ),
  (
    'ray_of_frost_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/ray_of_frost_1.webp'
  ),
  (
    'melfs_acid_arrow_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/melfs_acid_arrow_1.webp'
  ),
  (
    'flaming_arrows_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/flaming_arrows_1.webp'
  ),
  (
    'burning_hands_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/burning_hands_1.webp'
  ),
  (
    'call_from_the_grave_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/call_from_the_grave_1.webp'
  ),
  (
    'voices_of_the_damned_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/voices_of_the_damned_1.webp'
  ),
  (
    'dazzling_light_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/dazzling_light_1.webp'
  ),
  (
    'smothering_mist_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/smothering_mist_1.webp'
  ),
  (
    'brutal_betrayal_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/brutal_betrayal_1.webp'
  ),
  (
    'magic_loss_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/magic_loss_1.webp'
  ),
  (
    'blanket_of_flames_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/blanket_of_flames_1.webp'
  ),
  (
    'orb_of_lucid_vision_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/orb_of_lucid_vision_1.webp'
  ),
  (
    'boccobs_cloak_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/boccobs_cloak_1.webp'
  ),
  (
    'yonddalla_amulet_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/yonddalla_amulet_1.webp'
  ),
  (
    'ring_of_shadows_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/ring_of_shadows_1.webp'
  ),
  (
    'summoners_horn_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/summoners_horn_1.webp'
  ),
  (
    'bark_skin_cloak_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/bark_skin_cloak_1.webp'
  ),
  (
    'olidammara_amulet_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/olidammara_amulet_1.webp'
  ),
  (
    'potion_of_weakness_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/potion_of_weakness_1.webp'
  ),
  (
    'smoke_shadow_potion_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/smoke_shadow_potion_1.webp'
  ),
  (
    'kords_blessing_potion_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/kords_blessing_potion_1.webp'
  ),
  (
    'imperious_hand_potion_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/imperious_hand_potion_1.webp'
  ),
  (
    'potion_of_laughter_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/potion_of_laughter_1.webp'
  ),
  (
    'olidammara_wisdom_potion_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/olidammara_wisdom_potion_1.webp'
  ),
  (
    'partial_restoration_potion_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/partial_restoration_potion_1.webp'
  ),
  (
    'initiative_potion_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/initiative_potion_1.webp'
  ),
  (
    'ultimate_restoration_potion_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/ultimate_restoration_potion_1.webp'
  ),
  (
    'light_healing_potion_1',
    'https://jergauth-dnd-assets.s3.eu-west-3.amazonaws.com/light_healing_potion_1.webp'
  );